apiVersion: v1
kind: Service
metadata:
  name: mini-finance-service
spec:
  type: LoadBalancer  # 這會觸發 AWS 建立 ALB
  selector:
    app: mini-finance # 必須與 Deployment 的 label 一致
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80